#!/bin/bash

make
gcc test/$1 lib.o -m32 -o b.out
./b.out > gtest
gcc -E test/$1 -o prep
./cstr < prep > test.s
gcc test.s lib.o -m32
./a.out > ctest
NUMLINES=$(diff ctest gtest | wc -l)
if [ $NUMLINES -eq 0 ] ; then
	echo "Success!"
	rm gtest ctest test.s
else 
	echo "Failed"
	diff ctest gtest
fi
rm a.out b.out prep
